fixed dropdown issue on tables issue #1249
tabler/tabler pull request #1269
Opened 2022-09-20 14:20 UTC by Santanu-dev

![image](https://user-images.githubusercontent.com/106900914/191281336-63fbb48f-fa72-46d5-b0ae-7f16cdb4d0bd.png)

2022-09-21 20:38 UTC, codecalm requested changes

2022-09-21 20:38 UTC, codecalm commented on src/js/src/dropdown.js
> +	return new Dropdown(dropdownTriggerEl, oprions);
rename `oprions` to `options`

2022-09-25 05:54 UTC, Santanu-dev commented on src/js/src/dropdown.js
> +	return new Dropdown(dropdownTriggerEl, oprions);
> rename `oprions` to `options`

Done

2022-09-26 20:13 UTC, codecalm commented
works fine, thank you! :)

2022-09-26 20:13 UTC, merged