Replace `divide(...)` with `math.div` in the SCSS files
tabler/tabler pull request #976
Opened 2021-12-16 17:59 UTC by paulftw

Honestly, I could not understand how `divide($foo, $bar)` works in `@tabler/core` but for some reason it doesn't work when I `@use "@tabler/core/.../_variables.scss"` in my project.

Based on the [SASS deprecation notice](https://sass-lang.com/documentation/breaking-changes/slash-div) `math.div` is the way to go regardless.
WDYT about this change?

2021-12-16 19:59 UTC, codecalm requested changes

2021-12-16 19:59 UTC, codecalm commented on src/pages/_plugins/jekyll-filters.rb
> -    def divide(value, number)
it's jekyll filter, not sass mizin, you cannot remove it, becaouse for example this line will be not work: 

```
{% assign all-days = days | minus: start-day | plus: 1 | divide: 7.0 | ceil | times: 7 %}
```

2021-12-16 20:00 UTC, codecalm commented
`divide($foo, $bar)` is made in bootstrap core, Tabler just use it

2022-01-07 08:47 UTC, rjd22 commented
@codecalm I reverted the divide removal. I'm not sure you want to merge this even then since it's build based on a misconception so I leave merging or closing to you :)

2022-01-11 10:59 UTC, paulftw commented
@codecalm  @rjd22  this branch had conflicts, and in the end I decided it was easier to start a new one (don't ask).

I've provided more detailed rationale there and no longer touch jekyll-filters

Please see #994

2022-01-11 10:59 UTC, closed without merging